POST http://localhost/documents/refresh
X-API-KEY: local-key

###

GET http://localhost/documents
X-API-KEY: local-key

###

GET http://localhost/documents/1
X-API-KEY: local-key

###

POST http://localhost/documents/1/ask?prompt=O%20czym%20jest%20ten%20dokument
X-API-KEY: local-key
